global:
  scrape_interval: 1s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - "alertmanager:9093"

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: "metrics-app"
    static_configs:
      - targets: ["metrics-app:8000"]

